
require 'pp'
require 'onyx/env'
require 'onyx/lexer'
require 'onyx/nodes'
require 'onyx/obj/block'
require 'onyx/obj/object'
require 'onyx/obj/class'
require 'onyx/obj/method'
require 'onyx/obj/ruby'
require 'onyx/obj/super'
require 'onyx/parser'
require 'onyx/cont'
require 'onyx/prim'
require 'onyx/interp'

